-- Database Synchronization Script for Project Management V3
-- This script aligns the database schema with the Prisma definition.

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Sync projects table
DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
  `id` varchar(36) NOT NULL,
  `code` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `type` enum('domestic','overseas') DEFAULT 'domestic',
  `customer_id` varchar(36) DEFAULT NULL,
  `customer_name` varchar(200) DEFAULT NULL,
  `manager_id` varchar(36) DEFAULT NULL,
  `manager` varchar(100) DEFAULT NULL,
  `technical_lead_id` varchar(36) DEFAULT NULL,
  `status` enum('proposal','in_progress','completed','paused','delayed') DEFAULT 'proposal',
  `progress` int DEFAULT '0',
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `budget` decimal(15,2) DEFAULT '0.00',
  `country` varchar(50) DEFAULT '中国',
  `address` text,
  `description` text,
  `attachments` text,
  `organization_id` varchar(36) DEFAULT NULL,
  `approval_mode` varchar(50) DEFAULT 'workflow',
  `phase` varchar(50) DEFAULT NULL,
  `phase_start_date` date DEFAULT NULL,
  `phase_end_date` date DEFAULT NULL,
  `estimated_days` int DEFAULT '0',
  `remaining_days` int DEFAULT '0',
  `area` decimal(10,2) DEFAULT '0.00',
  `capacity` decimal(10,2) DEFAULT '0.00',
  `rack_count` int DEFAULT '0',
  `rack_power` decimal(5,2) DEFAULT '0.00',
  `power_arch` text,
  `hvac_arch` text,
  `fire_arch` text,
  `weak_arch` text,
  `building_area` decimal(10,2) DEFAULT NULL,
  `it_capacity` decimal(10,2) DEFAULT NULL,
  `cabinet_count` int DEFAULT NULL,
  `cabinet_power` decimal(10,2) DEFAULT NULL,
  `power_architecture` text,
  `hvac_architecture` text,
  `fire_architecture` text,
  `weak_electric_architecture` text,
  `end_customer` varchar(200) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `idx_projects_country` (`country`),
  KEY `idx_projects_customer` (`customer_id`),
  KEY `idx_projects_manager` (`manager_id`),
  KEY `idx_projects_status_start_date` (`status`,`start_date`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Sync equipment_instances table
DROP TABLE IF EXISTS `equipment_instances`;
CREATE TABLE `equipment_instances` (
  `id` varchar(36) NOT NULL,
  `manage_code` varchar(50) DEFAULT NULL,
  `equipment_name` varchar(200) NOT NULL,
  `model_no` varchar(100) NOT NULL,
  `category` enum('instrument','fake_load','cable','accessory') NOT NULL,
  `manufacturer` varchar(200) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `serial_number` varchar(100) DEFAULT NULL,
  `factory_serial_no` varchar(100) DEFAULT NULL,
  `tracking_type` enum('SERIALIZED','BATCH') DEFAULT 'SERIALIZED',
  `quantity` int DEFAULT '1',
  `unit` varchar(20) DEFAULT '台',
  `location_id` varchar(36) DEFAULT NULL,
  `location_status` enum('warehouse','in_project','in_transit','maintenance','scrapped') DEFAULT 'warehouse',
  `health_status` enum('normal','affected','broken','scrapped') DEFAULT 'normal',
  `usage_status` enum('idle','in_use','lost','scrapped','sold') DEFAULT 'idle',
  `keeper_id` varchar(36) DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `purchase_price` decimal(12,2) DEFAULT NULL,
  `calibration_expiry` date DEFAULT NULL,
  `certificate_no` varchar(100) DEFAULT NULL,
  `certificate_issuer` varchar(200) DEFAULT NULL,
  `supplier` varchar(200) DEFAULT NULL,
  `technical_params` text,
  `technical_doc` text,
  `attachment` varchar(500) DEFAULT NULL,
  `attachments` json DEFAULT NULL,
  `notes` text,
  `has_accessories` tinyint(1) DEFAULT '0',
  `accessory_count` int DEFAULT '0',
  `version` int NOT NULL DEFAULT '1',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `manage_code` (`manage_code`),
  KEY `idx_equipment` (`equipment_name`,`model_no`),
  KEY `idx_equipment_tracking_type` (`tracking_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Sync employees table
DROP TABLE IF EXISTS `employees`;
CREATE TABLE `employees` (
  `id` varchar(36) NOT NULL,
  `employee_no` varchar(50) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `gender` enum('male','female') DEFAULT NULL,
  `phone` varchar(20) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `department_id` varchar(36) DEFAULT NULL,
  `position` varchar(100) NOT NULL,
  `user_id` varchar(36) DEFAULT NULL,
  `status` enum('active','resigned','probation') DEFAULT 'active',
  `current_status` enum('on_duty','leave','business_trip','other') DEFAULT 'on_duty',
  `hire_date` date NOT NULL,
  `leave_date` date DEFAULT NULL,
  `role` enum('admin','project_manager','hr_manager','equipment_manager','implementer','user') DEFAULT 'user',
  `daily_cost` decimal(10,2) DEFAULT NULL,
  `skills` json DEFAULT NULL,
  `avatar_color` varchar(20) DEFAULT NULL,
  `data_permission` enum('self','department','all') DEFAULT 'self',
  `employee_type` enum('full_time','part_time','outsourced') DEFAULT 'full_time',
  `third_party_id` varchar(100) DEFAULT NULL,
  `third_party_source` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_no` (`employee_no`),
  KEY `idx_dept` (`department_id`),
  KEY `idx_employees_department_status` (`department_id`,`status`),
  KEY `idx_employees_user_id` (`user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
